/**
 * Frontend build for Cloudflare Pages.
 *
 * The site is vanilla ES modules with no bundler: pages import each other over absolute
 * paths and there is nothing to transpile or minify. So this build does the two jobs a static
 * host actually needs:
 *
 *   1. validate that every absolute href/src referenced by a page resolves to a real file,
 *      which catches a renamed or deleted asset before deployment;
 *   2. copy the tree into dist/ and emit the runtime API configuration.
 *
 * No dependencies, so `npm install` works offline and cannot pull a supply-chain risk.
 */
import { createHash } from 'node:crypto';
import { cp, mkdir, readFile, readdir, rm, stat, writeFile } from 'node:fs/promises';
import { dirname, extname, join, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = dirname(fileURLToPath(import.meta.url));
const DIST = join(ROOT, 'dist');
/* Cloudflare Pages: "Build command" npm run build, "Build output directory" dist.
   Build tooling is excluded so the deployed bundle holds only pages and assets. */
const SKIP = new Set(['dist', 'node_modules', '.git',
  'build.mjs', 'package.json', 'package-lock.json',
  '.env', '.env.local', '.env.example', '.DS_Store']);

const ASSET_EXT = new Set(['.html', '.js', '.mjs', '.css', '.svg', '.png', '.jpg', '.jpeg',
  '.gif', '.webp', '.ico', '.json', '.woff', '.woff2', '.mp4', '.webm', '.mp3', '.m4a', '.txt', '.md']);

async function walk(dir, out = []) {
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    if (SKIP.has(entry.name)) continue;
    const full = join(dir, entry.name);
    if (entry.isDirectory()) await walk(full, out);
    else out.push(full);
  }
  return out;
}

/** Absolute references look like href="/shared/base.css"; a leading / is site-root here. */
function absoluteRefs(html) {
  const refs = [];
  for (const match of html.matchAll(/(?:href|src)\s*=\s*"(\/[^"]+)"/g)) refs.push(match[1]);
  return refs;
}

async function validate(files) {
  const present = new Set(files.map((file) => `/${relative(ROOT, file).split('\\').join('/')}`));
  const problems = [];

  for (const file of files) {
    if (extname(file) !== '.html') continue;
    const html = await readFile(file, 'utf8');
    for (const ref of absoluteRefs(html)) {
      /* A query string or hash is still the same asset on disk. */
      const clean = ref.split(/[?#]/)[0];
      if (SKIP.has(clean.split('/')[1])) continue;
      if (present.has(clean)) continue;
      /* Directory routes are served by the API, not by a file on disk: '/' is the guest home
         and '/admin/' is a redirect. They legitimately have no static counterpart. */
      if (clean.endsWith('/')) continue;
      /* /user/groups/ is a directory route, not a file, so accept it when it holds index.html. */
      if (files.some((f) => `/${relative(ROOT, f).split('\\').join('/')}` === `${clean}index.html`)) continue;
      problems.push(`${relative(ROOT, file)} -> ${clean}`);
    }
  }
  return problems;
}

/**
 * Runtime configuration. Emitted as a plain script so pages can load it before any module and
 * api.js can read the base from the global. An empty base means "same origin", which is what
 * the Express server provides today.
 */
function configScript() {
  const base = String(process.env.API_BASE_URL || '').trim().replace(/\/+$/, '');
  return `/* Generated by frontend/build.mjs - do not edit. */
/* API_BASE_URL was ${base ? 'set' : 'empty (same-origin)'} at build time. */
globalThis.ECU_API_BASE = ${JSON.stringify(base)};
`;
}

/**
 * Workers Static Assets resolves "/" to <assets-dir>/index.html. This project has no page at the
 * dist root - the guest home is guest/index.html, which is where the API sends "/" as well - so
 * without this file every deployment answers 404 on its root URL.
 */
function rootRedirect() {
  return `<!DOCTYPE html>
<html lang="en" dir="ltr">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta http-equiv="refresh" content="0; url=/guest/">
<link rel="canonical" href="/guest/">
<title>ECU Students Assistant</title>
</head>
<body>
<p>Redirecting to <a href="/guest/">the home page</a>...</p>
<script>location.replace('/guest/');</script>
</body>
</html>
`;
}

async function main() {
  const files = await walk(ROOT);
  if (!files.some((f) => extname(f) === '.html')) {
    throw new Error('No HTML pages found under frontend/. Nothing to build.');
  }

  const problems = await validate(files);
  if (problems.length) {
    console.error('Broken references (fix these before deploying):');
    for (const problem of problems) console.error(`  ${problem}`);
    process.exit(1);
  }

  await rm(DIST, { recursive: true, force: true });
  for (const file of files) {
    const target = join(DIST, relative(ROOT, file));
    await mkdir(dirname(target), { recursive: true });
    await cp(file, target);
  }
  await writeFile(join(DIST, 'config.js'), configScript(), 'utf8');
  await writeFile(join(DIST, 'index.html'), rootRedirect(), 'utf8');

  const pages = files.filter((f) => extname(f) === '.html');
  const assets = files.filter((f) => ASSET_EXT.has(extname(f)));
  const total = (await Promise.all(files.map((f) => stat(f)))).reduce((n, s) => n + s.size, 0);

  /* Fingerprint of the whole tree, so two builds can be compared without diffing them. */
  const digest = createHash('sha256');
  for (const file of files.sort()) digest.update(relative(ROOT, file)).update(await readFile(file));

  console.log(`frontend : ${ROOT}`);
  console.log(`output   : ${DIST}`);
  console.log(`pages    : ${pages.length}`);
  console.log(`assets   : ${assets.length} (${(total / 1024).toFixed(1)} KB)`);
  console.log(`api base : ${process.env.API_BASE_URL ? process.env.API_BASE_URL : '(same origin)'}`);
  console.log(`build    : ${digest.digest('hex').slice(0, 12)}`);
  console.log('\nAll page references resolved. Ready for Cloudflare Pages.');
}

await main();